[package]
name = "rl_ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rapier2d = { version = "0.17.2", features = ["simd-stable"] }
raylib = "3.7.0"

[profile.release]
debug = true
